# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpWhoami < Formula
  desc "Show GCP identity (like aws sts get-caller-identity)"
  homepage "https://github.com/murarisumit/gcp-whoami"
  version "0.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/murarisumit/gcp-whoami/releases/download/v0.0.2/gcp-whoami_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "e94c8d869b083a483431a1933fe6fff62bfcaf091aa86d92e64233c9bf01fe63"

      def install
        bin.install "gcp-whoami"
      end
    end
    on_arm do
      url "https://github.com/murarisumit/gcp-whoami/releases/download/v0.0.2/gcp-whoami_0.0.2_Darwin_arm64.tar.gz"
      sha256 "3f284fe7aafe138abf36dc90dc832a6d1e995dca67c47db3aada5b01caee18dc"

      def install
        bin.install "gcp-whoami"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/murarisumit/gcp-whoami/releases/download/v0.0.2/gcp-whoami_0.0.2_Linux_x86_64.tar.gz"
        sha256 "b8f848fe303b4d51d587021548bf5d426c16212434850c42c2ee849ab4e8aef9"

        def install
          bin.install "gcp-whoami"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/murarisumit/gcp-whoami/releases/download/v0.0.2/gcp-whoami_0.0.2_Linux_arm64.tar.gz"
        sha256 "2aaea721d876101697f9384b792c3e8b7364d39b21cd497019fba64157f2aa40"

        def install
          bin.install "gcp-whoami"
        end
      end
    end
  end

  test do
    system "#{bin}/gcp-whoami", "--version"
  end
end
